import Vue from 'vue'
import { Button, Dialog, Rate, Tabbar, TabbarItem, NavBar, Field, Toast, CountDown, Search, Swipe, SwipeItem, Grid, GridItem, Divider, Sticky, Card, NoticeBar, Icon, Tab, Tabs, Sidebar, SidebarItem, ActionSheet, Cell, CellGroup, GoodsAction, GoodsActionIcon, GoodsActionButton, Stepper, Checkbox, CheckboxGroup, SubmitBar } from 'vant'

Vue.use(SubmitBar)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Stepper)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(ActionSheet)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Icon)
Vue.use(NoticeBar)
Vue.use(Card)
Vue.use(Sticky)
Vue.use(Divider)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Search)
Vue.use(CountDown)
Vue.use(Toast)
Vue.use(Field)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Dialog)
Vue.use(Button)
Vue.use(Rate)
